http:
  port: 8080

db:
#  uri: 'jdbc:postgresql://localhost:5432/grain_acceptance'
#  uri: 'localhost'
  name: 'banners'
  username: 'postgres'
  password: '1112'

cache:
  size: 1000
  TTL: 100000 #milisecond
